package ittalents.javaee1.models;

public enum VideoCategory {

    MOVIES_AND_ANIMATIONS, CARS_AND_VEHICLES, MUSIC, PETS_AND_ANIMALS, SPORT, JOURNEYS_AND_EVENTS,
    GAMES, COMEDY, PEOPLE_AND_BLOGS, ENTERTAINMENTS, NEWS_AND_POLITICS, EDUCATION, SCIENCE_AND_TECHNOLOGIES
}
